// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Model.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EMS.API.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "neha.kapoor@gmail.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kapoor",
                            Phone = "9988776655",
                            Salary = 550000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "Akash.verma@gmail.com",
                            FirstName = "Akash",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Verma",
                            Phone = "9011223344",
                            Salary = 720000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "sneha.prasad@gmail.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Prasad",
                            Phone = "9876501234",
                            Salary = 950000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Engineering",
                            Designation = "Senior Developer",
                            Email = "vikram.nair@gmail.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nair",
                            Phone = "9654321870",
                            Salary = 1100000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "ananya.singh@gmail.com",
                            FirstName = "Ananya",
                            JoinDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            Phone = "9345678901",
                            Salary = 580000m,
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Finance",
                            Designation = "Accounts Manager",
                            Email = "karthik.rajan@gmail.com",
                            FirstName = "Karthik",
                            JoinDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rajan",
                            Phone = "9812345670",
                            Salary = 800000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Department = "HR",
                            Designation = "Talent Acquisition Lead",
                            Email = "divya.kumar@gmail.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kumar",
                            Phone = "9701234568",
                            Salary = 690000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "meera.krishnan@gmail.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Krishnan",
                            Phone = "9567890123",
                            Salary = 730000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 11,
                            Department = "Finance",
                            Designation = "Tax Consultant",
                            Email = "suresh.babu@gmail.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2019, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Babu",
                            Phone = "9234567891",
                            Salary = 670000m,
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 12,
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "lakshmi.chandran@gmail.com",
                            FirstName = "Lakshmi",
                            JoinDate = new DateTime(2020, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chandran",
                            Phone = "9890123457",
                            Salary = 880000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 13,
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "amit.joshi@gmail.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joshi",
                            Phone = "9456789013",
                            Salary = 610000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 14,
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "pooja.ghosh@gmail.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ghosh",
                            Phone = "9678901236",
                            Salary = 920000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 15,
                            Department = "Operations",
                            Designation = "Logistics Coordinator",
                            Email = "rajesh.menon@gmail.com",
                            FirstName = "Rajesh",
                            JoinDate = new DateTime(2018, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Menon",
                            Phone = "9123789456",
                            Salary = 540000m,
                            Status = "Inactive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
